/*
*
* Chess Game
* Software Engineering II - Universidade Federal Fluminense
*
 */
package com.uff.chess.screens;

import javax.swing.WindowConstants;

/**
 *
 * @author Vynicius
 */
public class PawnPromotion extends javax.swing.JDialog {

    public enum PromotionPiece {
        ROOK, QUEEN, BISHOP, KNIGHT
    }

    private PromotionPiece promotionPiece;

    public PromotionPiece getPromotionPiece() {
        return promotionPiece;
    }

    /**
     * Creates new form PawnPromotion
     *
     * @param parent
     */
    public PawnPromotion(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        this.promotionPiece = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        queenButton = new javax.swing.JButton();
        knightButton = new javax.swing.JButton();
        rookButton = new javax.swing.JButton();
        bishopButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecione uma peça");
        setResizable(false);

        queenButton.setText("Rainha");
        queenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queenButtonActionPerformed(evt);
            }
        });

        knightButton.setText("Cavalo");
        knightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knightButtonActionPerformed(evt);
            }
        });

        rookButton.setText("Torre");
        rookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rookButtonActionPerformed(evt);
            }
        });

        bishopButton.setText("Bispo");
        bishopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bishopButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(queenButton)
                .addGap(18, 18, 18)
                .addComponent(knightButton)
                .addGap(18, 18, 18)
                .addComponent(rookButton)
                .addGap(18, 18, 18)
                .addComponent(bishopButton)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queenButton)
                    .addComponent(knightButton)
                    .addComponent(rookButton)
                    .addComponent(bishopButton))
                .addGap(53, 53, 53))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rookButtonActionPerformed
        this.promotionPiece = PromotionPiece.ROOK;
        this.dispose();
    }//GEN-LAST:event_rookButtonActionPerformed

    private void queenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queenButtonActionPerformed
        this.promotionPiece = PromotionPiece.QUEEN;
        this.dispose();
    }//GEN-LAST:event_queenButtonActionPerformed

    private void knightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knightButtonActionPerformed
        this.promotionPiece = PromotionPiece.KNIGHT;
        this.dispose();
    }//GEN-LAST:event_knightButtonActionPerformed

    private void bishopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bishopButtonActionPerformed
        this.promotionPiece = PromotionPiece.BISHOP;
        this.dispose();
    }//GEN-LAST:event_bishopButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bishopButton;
    private javax.swing.JButton knightButton;
    private javax.swing.JButton queenButton;
    private javax.swing.JButton rookButton;
    // End of variables declaration//GEN-END:variables
}
